# Generated by Django 5.0.2 on 2024-03-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_image_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='name',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_plan',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscriptionplan'),
        ),
    ]
